apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kserve
  namespace: kserve  
spec:
  interval: 10m  
  chart:
    spec:
      chart: kserve
      version: "v0.13.0"
      sourceRef:
        kind: HelmRepository
        name: kserve
        namespace: kserve