apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve-crd
  namespace: kserve
spec:
  chartRef:
    kind: OCIRepository
    name: kserve-crd
    namespace: flux-system
  interval: 1m
  values:
    replicaCount: 1