apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kserve-crd
  namespace: kserve
spec:
  interval: 1m  
  chart:
    spec:
      chart: kserve-crd
      version: "v0.14.0"
      sourceRef:
        kind: HelmRepository
        name: kserve
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kserve
  namespace: kserve  
spec:
  interval: 1m  
  chart:
    spec:
      chart: kserve
      version: "v0.14.0"
      sourceRef:
        kind: HelmRepository
        name: kserve
        namespace: flux-system
  values:
    kserve:
      storage:
        enableModelcar: "true"
        metricsaggregator:
          enableMetricAggregation: "false"
          enablePrometheusScraping: "true"
        controller:
          # KServe deployment mode: "Serverless", "RawDeployment".
          deploymentMode: "RawDeployment"
          securityContext:
            runAsNonRoot: true
          containerSecurityContext:
            runAsNonRoot: true
          rbacProxy:
            securityContext:
              runAsNonRoot: true
          gateway:
            # Ingress domain for RawDeployment mode, for Serverless it is configured in Knative.
            domain: mrt.com
          nodeSelector:
            agentpool: "normal"
          modelmesh:
            enabled: false