apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuberay-operator
  namespace: rayserve
spec:
  interval: 1m  
  chart:
    spec:
      chart: kuberay-operator
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: kuberay
        namespace: rayserve
  values:
    image:
      repository: quay.io/kuberay/operator:nightly
